Update to version 0.3.0
phac-nml/gasclustering pull request #30
Opened 2024-09-05 14:41 UTC by kylacochrane

Update `gasclustering` to version 0.3.0.

See `CHANGELOG.md` for updates.

2024-09-05 15:21 UTC, emarinier approved these changes

2024-09-05 16:12 UTC, apetkau requested changes
Looks good. One small change 😄

2024-09-05 16:12 UTC, apetkau commented on assets/samplesheet.csv
> +sample1,https://raw.githubusercontent.com/phac-nml/gasclustering/update/input_assure/tests/data/reports/sample1.mlst.json
Change test data back to `dev`

2024-09-05 19:10 UTC, apetkau approved these changes
Thanks so much.

2024-09-10 18:59 UTC, apetkau approved these changes
Looks great to me. Thanks so much Kyla 😄

2024-09-10 19:24 UTC, merged